// JavaScript source code
ServerEvents.tags('item', event => {

	event.add('forge:tfc_plank', 'tfc:wood/planks/sequoia')
	event.add('forge:tfc_plank', 'tfc:wood/planks/spruce')
	event.add('forge:tfc_plank', 'tfc:wood/planks/sycamore')
	event.add('forge:tfc_plank', 'tfc:wood/planks/white_cedar')
	event.add('forge:tfc_plank', 'tfc:wood/planks/willow')
	event.add('forge:tfc_plank', 'twilightforest:twilight_oak_planks')
	event.add('forge:tfc_plank', 'tfc:wood/planks/pine')
	event.add('forge:tfc_plank', 'tfc:wood/planks/palm')
	event.add('forge:tfc_plank', 'tfc:wood/planks/oak')
	event.add('forge:tfc_plank', 'tfc:wood/planks/maple')
	event.add('forge:tfc_plank', 'tfc:wood/planks/mangrove')
	event.add('forge:tfc_plank', 'tfc:wood/planks/kapok')
	event.add('forge:tfc_plank', 'tfc:wood/planks/hickory')
	event.add('forge:tfc_plank', 'tfc:wood/planks/acacia')
	event.add('forge:tfc_plank', 'tfc:wood/planks/ash')
	event.add('forge:tfc_plank', 'tfc:wood/planks/aspen')
	event.add('forge:tfc_plank', 'tfc:wood/planks/birch')
	event.add('forge:tfc_plank', 'tfc:wood/planks/blackwood')
	event.add('forge:tfc_plank', 'tfc:wood/planks/chestnut')
	event.add('forge:tfc_plank', 'tfc:wood/planks/douglas_fir')
	event.add('forge:tfc_plank', 'tfc:wood/planks/rosewood')
	event.add('forge:tfc_plank', 'twilightforest:canopy_planks')
	event.add('forge:tfc_plank', 'twilightforest:mangrove_planks')
	event.add('forge:tfc_plank', 'twilightforest:dark_planks')
	event.add('forge:tfc_plank', 'twilightforest:time_planks')
	event.add('forge:tfc_plank', 'twilightforest:transformation_planks')
event.add('forge:tfc_plank', 'twilightforest:mining_planks')
	})
